{
  "formatVersion": "1.1",
  "component": {
    "group": "com.frank1o3.franklylib",
    "module": "franklylib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "franklylib-1.0.1.jar",
          "url": "franklylib-1.0.1.jar",
          "size": 146097,
          "sha512": "86587e6e389d59924cb2a2fbfc70b0d5b2860c4044cfa1812f9677bc967a60a916e7e22a9708c85d346b28117790553c70ddd330524ccdea95ab1a0a2fe7d974",
          "sha256": "1df97890a9d870839344f2073261b44f683ae03c71b20702a13d61ba1aad6a28",
          "sha1": "bf39038bac23388362cc380d1320ba08804f9d66",
          "md5": "be813dc28252d4bffd691140f4e608dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "franklylib-1.0.1.jar",
          "url": "franklylib-1.0.1.jar",
          "size": 146097,
          "sha512": "86587e6e389d59924cb2a2fbfc70b0d5b2860c4044cfa1812f9677bc967a60a916e7e22a9708c85d346b28117790553c70ddd330524ccdea95ab1a0a2fe7d974",
          "sha256": "1df97890a9d870839344f2073261b44f683ae03c71b20702a13d61ba1aad6a28",
          "sha1": "bf39038bac23388362cc380d1320ba08804f9d66",
          "md5": "be813dc28252d4bffd691140f4e608dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "franklylib-1.0.1-sources.jar",
          "url": "franklylib-1.0.1-sources.jar",
          "size": 117040,
          "sha512": "e317979dc8791098209fc2d3cd81abbbe46cb0da8edf2646dca829a14c31b9eeea2f11e0b12f6a28a88ecd19f6371fafc69055e08777c4198f9ce690157cb862",
          "sha256": "1e2a0e442f74bc68ce99c86992f690805c911d3355e23f5fd9f5f92c6ce88c8a",
          "sha1": "f7e8da843b937f8e790f2641fca765265c4f679e",
          "md5": "6aa08c17556fa604df77866dcef2caf2"
        }
      ]
    }
  ]
}
